services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/linkbindb?schema=public
    depends_on:
      - db
    command: ["npm", "run", "dev"]

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: linkbindb
    ports:
      - '5432:5432'
    volumes:
      - db_data_dev:/var/lib/postgresql/data

volumes:
  db_data_dev:
